/*
 * This file is generated by jOOQ.
 */
package info.jab.ms.jooq.tables.daos;


import info.jab.ms.jooq.tables.FilmActor;
import info.jab.ms.jooq.tables.pojos.JooqFilmActor;
import info.jab.ms.jooq.tables.records.FilmActorRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class FilmActorRepository extends DAOImpl<FilmActorRecord, JooqFilmActor, Record2<Long, Long>> {

    /**
     * Create a new FilmActorRepository without any configuration
     */
    public FilmActorRepository() {
        super(FilmActor.FILM_ACTOR, JooqFilmActor.class);
    }

    /**
     * Create a new FilmActorRepository with an attached configuration
     */
    @Autowired
    public FilmActorRepository(Configuration configuration) {
        super(FilmActor.FILM_ACTOR, JooqFilmActor.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(JooqFilmActor object) {
        return compositeKeyRecord(object.getActorId(), object.getFilmId());
    }

    /**
     * Fetch records that have <code>actor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqFilmActor> fetchRangeOfActorId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FilmActor.FILM_ACTOR.ACTOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>actor_id IN (values)</code>
     */
    public List<JooqFilmActor> fetchByActorId(Long... values) {
        return fetch(FilmActor.FILM_ACTOR.ACTOR_ID, values);
    }

    /**
     * Fetch records that have <code>film_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqFilmActor> fetchRangeOfFilmId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FilmActor.FILM_ACTOR.FILM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>film_id IN (values)</code>
     */
    public List<JooqFilmActor> fetchByFilmId(Long... values) {
        return fetch(FilmActor.FILM_ACTOR.FILM_ID, values);
    }

    /**
     * Fetch records that have <code>last_update BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqFilmActor> fetchRangeOfLastUpdate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FilmActor.FILM_ACTOR.LAST_UPDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<JooqFilmActor> fetchByLastUpdate(LocalDateTime... values) {
        return fetch(FilmActor.FILM_ACTOR.LAST_UPDATE, values);
    }
}
