/*
 * This file is generated by jOOQ.
 */
package info.jab.ms.jooq.tables.daos;


import info.jab.ms.jooq.tables.Rental;
import info.jab.ms.jooq.tables.pojos.JooqRental;
import info.jab.ms.jooq.tables.records.RentalRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RentalRepository extends DAOImpl<RentalRecord, JooqRental, Long> {

    /**
     * Create a new RentalRepository without any configuration
     */
    public RentalRepository() {
        super(Rental.RENTAL, JooqRental.class);
    }

    /**
     * Create a new RentalRepository with an attached configuration
     */
    @Autowired
    public RentalRepository(Configuration configuration) {
        super(Rental.RENTAL, JooqRental.class, configuration);
    }

    @Override
    public Long getId(JooqRental object) {
        return object.getRentalId();
    }

    /**
     * Fetch records that have <code>rental_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfRentalId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Rental.RENTAL.RENTAL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rental_id IN (values)</code>
     */
    public List<JooqRental> fetchByRentalId(Long... values) {
        return fetch(Rental.RENTAL.RENTAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>rental_id = value</code>
     */
    public JooqRental fetchOneByRentalId(Long value) {
        return fetchOne(Rental.RENTAL.RENTAL_ID, value);
    }

    /**
     * Fetch a unique record that has <code>rental_id = value</code>
     */
    public Optional<JooqRental> fetchOptionalByRentalId(Long value) {
        return fetchOptional(Rental.RENTAL.RENTAL_ID, value);
    }

    /**
     * Fetch records that have <code>rental_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfRentalDate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Rental.RENTAL.RENTAL_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rental_date IN (values)</code>
     */
    public List<JooqRental> fetchByRentalDate(LocalDateTime... values) {
        return fetch(Rental.RENTAL.RENTAL_DATE, values);
    }

    /**
     * Fetch records that have <code>inventory_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfInventoryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Rental.RENTAL.INVENTORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>inventory_id IN (values)</code>
     */
    public List<JooqRental> fetchByInventoryId(Long... values) {
        return fetch(Rental.RENTAL.INVENTORY_ID, values);
    }

    /**
     * Fetch records that have <code>customer_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfCustomerId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Rental.RENTAL.CUSTOMER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<JooqRental> fetchByCustomerId(Long... values) {
        return fetch(Rental.RENTAL.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>return_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfReturnDate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Rental.RENTAL.RETURN_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>return_date IN (values)</code>
     */
    public List<JooqRental> fetchByReturnDate(LocalDateTime... values) {
        return fetch(Rental.RENTAL.RETURN_DATE, values);
    }

    /**
     * Fetch records that have <code>staff_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfStaffId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Rental.RENTAL.STAFF_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>staff_id IN (values)</code>
     */
    public List<JooqRental> fetchByStaffId(Long... values) {
        return fetch(Rental.RENTAL.STAFF_ID, values);
    }

    /**
     * Fetch records that have <code>last_update BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRental> fetchRangeOfLastUpdate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Rental.RENTAL.LAST_UPDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<JooqRental> fetchByLastUpdate(LocalDateTime... values) {
        return fetch(Rental.RENTAL.LAST_UPDATE, values);
    }
}
