/*
 * This file is generated by jOOQ.
 */
package info.jab.ms.jooq.tables.pojos;


import info.jab.ms.jooq.enums.MpaaRating;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqFilm implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long filmId;
    private String title;
    private String description;
    private Integer releaseYear;
    private Long languageId;
    private Long originalLanguageId;
    private Short rentalDuration;
    private BigDecimal rentalRate;
    private Short length;
    private BigDecimal replacementCost;
    private MpaaRating rating;
    private LocalDateTime lastUpdate;
    private String[] specialFeatures;
    private Object fulltext;

    public JooqFilm() {}

    public JooqFilm(JooqFilm value) {
        this.filmId = value.filmId;
        this.title = value.title;
        this.description = value.description;
        this.releaseYear = value.releaseYear;
        this.languageId = value.languageId;
        this.originalLanguageId = value.originalLanguageId;
        this.rentalDuration = value.rentalDuration;
        this.rentalRate = value.rentalRate;
        this.length = value.length;
        this.replacementCost = value.replacementCost;
        this.rating = value.rating;
        this.lastUpdate = value.lastUpdate;
        this.specialFeatures = value.specialFeatures;
        this.fulltext = value.fulltext;
    }

    public JooqFilm(
        Long filmId,
        String title,
        String description,
        Integer releaseYear,
        Long languageId,
        Long originalLanguageId,
        Short rentalDuration,
        BigDecimal rentalRate,
        Short length,
        BigDecimal replacementCost,
        MpaaRating rating,
        LocalDateTime lastUpdate,
        String[] specialFeatures,
        Object fulltext
    ) {
        this.filmId = filmId;
        this.title = title;
        this.description = description;
        this.releaseYear = releaseYear;
        this.languageId = languageId;
        this.originalLanguageId = originalLanguageId;
        this.rentalDuration = rentalDuration;
        this.rentalRate = rentalRate;
        this.length = length;
        this.replacementCost = replacementCost;
        this.rating = rating;
        this.lastUpdate = lastUpdate;
        this.specialFeatures = specialFeatures;
        this.fulltext = fulltext;
    }

    /**
     * Getter for <code>public.film.film_id</code>.
     */
    public Long getFilmId() {
        return this.filmId;
    }

    /**
     * Setter for <code>public.film.film_id</code>.
     */
    public void setFilmId(Long filmId) {
        this.filmId = filmId;
    }

    /**
     * Getter for <code>public.film.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.film.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.film.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.film.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.film.release_year</code>.
     */
    public Integer getReleaseYear() {
        return this.releaseYear;
    }

    /**
     * Setter for <code>public.film.release_year</code>.
     */
    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }

    /**
     * Getter for <code>public.film.language_id</code>.
     */
    public Long getLanguageId() {
        return this.languageId;
    }

    /**
     * Setter for <code>public.film.language_id</code>.
     */
    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    /**
     * Getter for <code>public.film.original_language_id</code>.
     */
    public Long getOriginalLanguageId() {
        return this.originalLanguageId;
    }

    /**
     * Setter for <code>public.film.original_language_id</code>.
     */
    public void setOriginalLanguageId(Long originalLanguageId) {
        this.originalLanguageId = originalLanguageId;
    }

    /**
     * Getter for <code>public.film.rental_duration</code>.
     */
    public Short getRentalDuration() {
        return this.rentalDuration;
    }

    /**
     * Setter for <code>public.film.rental_duration</code>.
     */
    public void setRentalDuration(Short rentalDuration) {
        this.rentalDuration = rentalDuration;
    }

    /**
     * Getter for <code>public.film.rental_rate</code>.
     */
    public BigDecimal getRentalRate() {
        return this.rentalRate;
    }

    /**
     * Setter for <code>public.film.rental_rate</code>.
     */
    public void setRentalRate(BigDecimal rentalRate) {
        this.rentalRate = rentalRate;
    }

    /**
     * Getter for <code>public.film.length</code>.
     */
    public Short getLength() {
        return this.length;
    }

    /**
     * Setter for <code>public.film.length</code>.
     */
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * Getter for <code>public.film.replacement_cost</code>.
     */
    public BigDecimal getReplacementCost() {
        return this.replacementCost;
    }

    /**
     * Setter for <code>public.film.replacement_cost</code>.
     */
    public void setReplacementCost(BigDecimal replacementCost) {
        this.replacementCost = replacementCost;
    }

    /**
     * Getter for <code>public.film.rating</code>.
     */
    public MpaaRating getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.film.rating</code>.
     */
    public void setRating(MpaaRating rating) {
        this.rating = rating;
    }

    /**
     * Getter for <code>public.film.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.film.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.film.special_features</code>.
     */
    public String[] getSpecialFeatures() {
        return this.specialFeatures;
    }

    /**
     * Setter for <code>public.film.special_features</code>.
     */
    public void setSpecialFeatures(String[] specialFeatures) {
        this.specialFeatures = specialFeatures;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getFulltext() {
        return this.fulltext;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setFulltext(Object fulltext) {
        this.fulltext = fulltext;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqFilm other = (JooqFilm) obj;
        if (this.filmId == null) {
            if (other.filmId != null)
                return false;
        }
        else if (!this.filmId.equals(other.filmId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.releaseYear == null) {
            if (other.releaseYear != null)
                return false;
        }
        else if (!this.releaseYear.equals(other.releaseYear))
            return false;
        if (this.languageId == null) {
            if (other.languageId != null)
                return false;
        }
        else if (!this.languageId.equals(other.languageId))
            return false;
        if (this.originalLanguageId == null) {
            if (other.originalLanguageId != null)
                return false;
        }
        else if (!this.originalLanguageId.equals(other.originalLanguageId))
            return false;
        if (this.rentalDuration == null) {
            if (other.rentalDuration != null)
                return false;
        }
        else if (!this.rentalDuration.equals(other.rentalDuration))
            return false;
        if (this.rentalRate == null) {
            if (other.rentalRate != null)
                return false;
        }
        else if (!this.rentalRate.equals(other.rentalRate))
            return false;
        if (this.length == null) {
            if (other.length != null)
                return false;
        }
        else if (!this.length.equals(other.length))
            return false;
        if (this.replacementCost == null) {
            if (other.replacementCost != null)
                return false;
        }
        else if (!this.replacementCost.equals(other.replacementCost))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        if (this.specialFeatures == null) {
            if (other.specialFeatures != null)
                return false;
        }
        else if (!Arrays.equals(this.specialFeatures, other.specialFeatures))
            return false;
        if (this.fulltext == null) {
            if (other.fulltext != null)
                return false;
        }
        else if (!this.fulltext.equals(other.fulltext))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.filmId == null) ? 0 : this.filmId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.releaseYear == null) ? 0 : this.releaseYear.hashCode());
        result = prime * result + ((this.languageId == null) ? 0 : this.languageId.hashCode());
        result = prime * result + ((this.originalLanguageId == null) ? 0 : this.originalLanguageId.hashCode());
        result = prime * result + ((this.rentalDuration == null) ? 0 : this.rentalDuration.hashCode());
        result = prime * result + ((this.rentalRate == null) ? 0 : this.rentalRate.hashCode());
        result = prime * result + ((this.length == null) ? 0 : this.length.hashCode());
        result = prime * result + ((this.replacementCost == null) ? 0 : this.replacementCost.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.specialFeatures == null) ? 0 : Arrays.hashCode(this.specialFeatures));
        result = prime * result + ((this.fulltext == null) ? 0 : this.fulltext.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqFilm (");

        sb.append(filmId);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(releaseYear);
        sb.append(", ").append(languageId);
        sb.append(", ").append(originalLanguageId);
        sb.append(", ").append(rentalDuration);
        sb.append(", ").append(rentalRate);
        sb.append(", ").append(length);
        sb.append(", ").append(replacementCost);
        sb.append(", ").append(rating);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(Arrays.toString(specialFeatures));
        sb.append(", ").append(fulltext);

        sb.append(")");
        return sb.toString();
    }
}
