/*
 * This file is generated by jOOQ.
 */
package info.jab.ms.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqLanguage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long languageId;
    private String name;
    private LocalDateTime lastUpdate;

    public JooqLanguage() {}

    public JooqLanguage(JooqLanguage value) {
        this.languageId = value.languageId;
        this.name = value.name;
        this.lastUpdate = value.lastUpdate;
    }

    public JooqLanguage(
        Long languageId,
        String name,
        LocalDateTime lastUpdate
    ) {
        this.languageId = languageId;
        this.name = name;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.language.language_id</code>.
     */
    public Long getLanguageId() {
        return this.languageId;
    }

    /**
     * Setter for <code>public.language.language_id</code>.
     */
    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    /**
     * Getter for <code>public.language.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.language.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.language.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.language.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqLanguage other = (JooqLanguage) obj;
        if (this.languageId == null) {
            if (other.languageId != null)
                return false;
        }
        else if (!this.languageId.equals(other.languageId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.languageId == null) ? 0 : this.languageId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqLanguage (");

        sb.append(languageId);
        sb.append(", ").append(name);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
