/*
 * This file is generated by jOOQ.
 */
package info.jab.ms.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqFilmNotInStock implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer pFilmCount;

    public JooqFilmNotInStock() {}

    public JooqFilmNotInStock(JooqFilmNotInStock value) {
        this.pFilmCount = value.pFilmCount;
    }

    public JooqFilmNotInStock(
        Integer pFilmCount
    ) {
        this.pFilmCount = pFilmCount;
    }

    /**
     * Getter for <code>public.film_not_in_stock.p_film_count</code>.
     */
    public Integer getPFilmCount() {
        return this.pFilmCount;
    }

    /**
     * Setter for <code>public.film_not_in_stock.p_film_count</code>.
     */
    public void setPFilmCount(Integer pFilmCount) {
        this.pFilmCount = pFilmCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqFilmNotInStock other = (JooqFilmNotInStock) obj;
        if (this.pFilmCount == null) {
            if (other.pFilmCount != null)
                return false;
        }
        else if (!this.pFilmCount.equals(other.pFilmCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pFilmCount == null) ? 0 : this.pFilmCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqFilmNotInStock (");

        sb.append(pFilmCount);

        sb.append(")");
        return sb.toString();
    }
}
